-- ============================================================
-- Honda Islamabad — Parts & Service Management — Supabase schema (hw_ prefix)
-- Multi-tenant: har row shop_id ke saath. RLS ON, no policies
-- (access sirf service key se, Cloudflare Function ke zariye).
-- Idempotent: dobara chala saktay hain (if not exists / create or replace).
-- Supabase SQL editor mein poora block paste kar ke Run karein.
-- ============================================================

-- ---------- core: shop + logins ----------
create table if not exists hw_shops (
  id          bigint generated by default as identity primary key,
  name        text not null,
  tagline     text default '',
  phone       text default '',
  address     text default '',
  inv_no      integer default 4000,          -- Parts Sale invoice counter (INV-2026-xxxx)
  po_no       integer default 1000,          -- Purchase order counter (PO-2026-xxxx)
  srv_no      integer default 3000,          -- Service job counter (SRV-xxxx)
  status      text default 'active' check (status in ('trial','active','blocked')),
  trial_ends  date,
  created_at  timestamptz default now()
);
-- agar table pehle se hai to naye counter columns add ho jayein:
alter table hw_shops add column if not exists po_no  integer default 1000;
alter table hw_shops add column if not exists srv_no integer default 3000;

create table if not exists hw_users (
  id       bigint generated by default as identity primary key,
  shop_id  bigint not null references hw_shops(id) on delete cascade,
  username text not null unique,
  password text not null,
  name     text default '',
  role     text default 'cashier'
);
create index if not exists ix_hwusers_shop on hw_users(shop_id);

-- ---------- parts / stock ----------
create table if not exists hw_parts (
  id       bigint generated by default as identity primary key,
  shop_id  bigint not null references hw_shops(id) on delete cascade,
  name     text not null,
  nick     text default '',
  model    text default '',
  code     text default '',
  loc      text default '',                 -- shelf / bin
  stock    numeric default 0,
  min_qty  numeric default 0,               -- reorder level
  cost     numeric default 0,               -- purchase price
  price    numeric default 0,               -- sale price
  ts       bigint default 0
);
create index if not exists ix_hwparts_shop on hw_parts(shop_id);

-- ---------- suppliers ----------
create table if not exists hw_suppliers (
  id        bigint generated by default as identity primary key,
  shop_id   bigint not null references hw_shops(id) on delete cascade,
  name      text not null,
  phone     text default '',
  address   text default '',
  bal       numeric default 0,              -- outstanding payable to supplier
  incentive numeric default 0,              -- available supplier incentive/credit
  ts        bigint default 0
);
create index if not exists ix_hwsupp_shop on hw_suppliers(shop_id);

-- ---------- mechanics + ledger (advance / recover / settle) ----------
create table if not exists hw_mechanics (
  id         bigint generated by default as identity primary key,
  shop_id    bigint not null references hw_shops(id) on delete cascade,
  name       text not null,
  mobile     text default '',
  cnic       text default '',
  dob        text default '',
  designation text default 'Mechanic',
  commission numeric default 40,            -- % of labour that becomes mechanic wage
  active     boolean default true,
  ts         bigint default 0
);
create index if not exists ix_hwmech_shop on hw_mechanics(shop_id);

create table if not exists hw_mech_ledger (
  id       bigint generated by default as identity primary key,
  shop_id  bigint not null references hw_shops(id) on delete cascade,
  mech_id  bigint not null references hw_mechanics(id) on delete cascade,
  kind     text default 'settle' check (kind in ('advance','recover','settle')),
  amt      numeric default 0,
  date     text default '',
  note     text default '',
  ts       bigint default 0
);
create index if not exists ix_hwmechl_shop on hw_mech_ledger(shop_id);

-- ---------- employees + ledger (salary / advance / recover) ----------
create table if not exists hw_employees (
  id         bigint generated by default as identity primary key,
  shop_id    bigint not null references hw_shops(id) on delete cascade,
  code       text default '',               -- EMP-001
  name       text not null,
  designation text default '',
  role       text default '',               -- Cashier / Salesman / Admin / Helper
  salary     numeric default 0,             -- monthly
  active     boolean default true,
  ts         bigint default 0
);
create index if not exists ix_hwemp_shop on hw_employees(shop_id);

create table if not exists hw_emp_ledger (
  id       bigint generated by default as identity primary key,
  shop_id  bigint not null references hw_shops(id) on delete cascade,
  emp_id   bigint not null references hw_employees(id) on delete cascade,
  kind     text default 'salary' check (kind in ('salary','advance','recover')),
  amt      numeric default 0,
  month    text default '',                 -- YYYY-MM (for salary)
  date     text default '',
  note     text default '',
  ts       bigint default 0
);
create index if not exists ix_hwempl_shop on hw_emp_ledger(shop_id);

-- ---------- expenses ----------
create table if not exists hw_expenses (
  id       bigint generated by default as identity primary key,
  shop_id  bigint not null references hw_shops(id) on delete cascade,
  title    text default '',
  cat      text default 'General',
  amt      numeric default 0,
  date     text default '',
  ts       bigint default 0
);
create index if not exists ix_hwexp_shop on hw_expenses(shop_id);

-- ---------- kharadia (outsourced work: paid out vs charged) ----------
create table if not exists hw_kharadia (
  id       bigint generated by default as identity primary key,
  shop_id  bigint not null references hw_shops(id) on delete cascade,
  descr    text default '',
  customer text default '',
  bike     text default '',
  paid_out numeric default 0,               -- to outsourcer
  charged  numeric default 0,               -- to customer
  date     text default '',
  ts       bigint default 0
);
create index if not exists ix_hwkhar_shop on hw_kharadia(shop_id);

-- ---------- purchases (header + items) ----------
create table if not exists hw_purchases (
  id        bigint generated by default as identity primary key,
  shop_id   bigint not null references hw_shops(id) on delete cascade,
  po        text default '',                -- PO-2026-1099
  supp_id   bigint,
  supp_name text default '',
  inv_no    text default '',                -- supplier invoice
  date      text default '',
  notes     text default '',
  amount    numeric default 0,
  paid      numeric default 0,              -- own cash paid
  incentive_used numeric default 0,         -- supplier incentive applied
  status    text default 'received' check (status in ('received','partial','pending')),
  ts        bigint default 0
);
create index if not exists ix_hwpur_shop on hw_purchases(shop_id);

create table if not exists hw_purchase_items (
  id        bigint generated by default as identity primary key,
  shop_id   bigint not null references hw_shops(id) on delete cascade,
  pur_id    bigint not null references hw_purchases(id) on delete cascade,
  part_id   bigint,
  part_name text default '',
  qty       numeric default 0,
  price     numeric default 0
);
create index if not exists ix_hwpuri_shop on hw_purchase_items(shop_id);
create index if not exists ix_hwpuri_pur on hw_purchase_items(pur_id);

-- ---------- parts sale (header + items) ----------
create table if not exists hw_sales (
  id       bigint generated by default as identity primary key,
  shop_id  bigint not null references hw_shops(id) on delete cascade,
  inv      text default '',                 -- INV-2026-4464
  customer text default '',
  phone    text default '',
  salesman text default '',
  date     text default '',
  subtotal numeric default 0,
  discount numeric default 0,
  total    numeric default 0,
  pay      text default 'Cash',
  ts       bigint default 0
);
create index if not exists ix_hwsale_shop on hw_sales(shop_id);

create table if not exists hw_sale_items (
  id        bigint generated by default as identity primary key,
  shop_id   bigint not null references hw_shops(id) on delete cascade,
  sale_id   bigint not null references hw_sales(id) on delete cascade,
  part_id   bigint,
  part_name text default '',
  qty       numeric default 0,
  cost      numeric default 0,
  price     numeric default 0
);
create index if not exists ix_hwsalei_shop on hw_sale_items(shop_id);
create index if not exists ix_hwsalei_sale on hw_sale_items(sale_id);

-- ---------- service jobs (header + parts used) ----------
create table if not exists hw_jobs (
  id          bigint generated by default as identity primary key,
  shop_id     bigint not null references hw_shops(id) on delete cascade,
  job         text default '',              -- SRV-3266
  customer    text default '',
  phone       text default '',
  bike_no     text default '',
  bike_model  text default '',
  chassis     text default '',
  engine      text default '',
  mech_id     bigint,
  mech_name   text default '',
  salesman    text default '',
  status      text default 'open' check (status in ('open','closed')),
  parts_total numeric default 0,            -- gross parts (sale price)
  parts_cost  numeric default 0,            -- purchase cost of parts
  discount    numeric default 0,            -- parts discount
  labour      numeric default 0,
  total       numeric default 0,            -- net parts + labour
  pay         text default '',
  entry_ts    bigint default 0,
  exit_ts     bigint default 0,
  ts          bigint default 0
);
create index if not exists ix_hwjobs_shop on hw_jobs(shop_id);

create table if not exists hw_job_parts (
  id        bigint generated by default as identity primary key,
  shop_id   bigint not null references hw_shops(id) on delete cascade,
  job_id    bigint not null references hw_jobs(id) on delete cascade,
  part_id   bigint,
  part_name text default '',
  qty       numeric default 0,
  cost      numeric default 0,
  price     numeric default 0
);
create index if not exists ix_hwjobp_shop on hw_job_parts(shop_id);
create index if not exists ix_hwjobp_job on hw_job_parts(job_id);

-- ---------- warranty claims (Honda reimbursement, linked to a job) ----------
create table if not exists hw_warranty (
  id       bigint generated by default as identity primary key,
  shop_id  bigint not null references hw_shops(id) on delete cascade,
  job_id   bigint,
  job_no   text default '',
  customer text default '',
  bike     text default '',
  descr    text default '',
  date     text default '',
  claimed  numeric default 0,
  approved numeric default 0,
  status   text default 'pending' check (status in ('pending','approved','paid','rejected')),
  ts       bigint default 0
);
create index if not exists ix_hwwar_shop on hw_warranty(shop_id);

-- ---------- RLS on (deny by default; service key bypasses) ----------
alter table hw_shops           enable row level security;
alter table hw_users           enable row level security;
alter table hw_parts           enable row level security;
alter table hw_suppliers       enable row level security;
alter table hw_mechanics       enable row level security;
alter table hw_mech_ledger     enable row level security;
alter table hw_employees       enable row level security;
alter table hw_emp_ledger      enable row level security;
alter table hw_expenses        enable row level security;
alter table hw_kharadia        enable row level security;
alter table hw_purchases       enable row level security;
alter table hw_purchase_items  enable row level security;
alter table hw_sales           enable row level security;
alter table hw_sale_items      enable row level security;
alter table hw_jobs            enable row level security;
alter table hw_job_parts       enable row level security;
alter table hw_warranty        enable row level security;

-- ============================================================
-- bootstrap: ek call mein shop ka poora data (app load par).
-- Bari tables newest-first + limit (naye client ke liye kaafi;
-- bohot bara data ho to aage server-side paging add ho sakti hai).
-- ============================================================
create or replace function fn_hw_bootstrap(p_sid bigint)
returns jsonb language sql as $fn$
select jsonb_build_object(
  'shopInfo', (select jsonb_build_object('name',name,'tagline',tagline,'phone',phone,'address',address) from hw_shops where id = p_sid),
  'counters', (select jsonb_build_object('inv',inv_no,'po',po_no,'srv',srv_no) from hw_shops where id = p_sid),
  'status',   (select status from hw_shops where id = p_sid),
  'users',    coalesce((select jsonb_agg(jsonb_build_object('id',id,'username',username,'name',name,'role',role) order by id) from hw_users where shop_id = p_sid),'[]'::jsonb),
  'parts',    coalesce((select jsonb_agg(to_jsonb(x)-'shop_id' order by x.name) from (select * from hw_parts where shop_id=p_sid order by name limit 5000) x),'[]'::jsonb),
  'suppliers',coalesce((select jsonb_agg(to_jsonb(x)-'shop_id' order by x.name) from (select * from hw_suppliers where shop_id=p_sid) x),'[]'::jsonb),
  'mechanics',coalesce((select jsonb_agg(to_jsonb(x)-'shop_id' order by x.name) from (select * from hw_mechanics where shop_id=p_sid) x),'[]'::jsonb),
  'mechLedger',coalesce((select jsonb_agg(to_jsonb(x)-'shop_id' order by x.id) from (select * from hw_mech_ledger where shop_id=p_sid order by id desc limit 3000) x),'[]'::jsonb),
  'employees',coalesce((select jsonb_agg(to_jsonb(x)-'shop_id' order by x.code) from (select * from hw_employees where shop_id=p_sid) x),'[]'::jsonb),
  'empLedger',coalesce((select jsonb_agg(to_jsonb(x)-'shop_id' order by x.id) from (select * from hw_emp_ledger where shop_id=p_sid order by id desc limit 3000) x),'[]'::jsonb),
  'expenses', coalesce((select jsonb_agg(to_jsonb(x)-'shop_id' order by x.id desc) from (select * from hw_expenses where shop_id=p_sid order by id desc limit 3000) x),'[]'::jsonb),
  'kharadia', coalesce((select jsonb_agg(to_jsonb(x)-'shop_id' order by x.id desc) from (select * from hw_kharadia where shop_id=p_sid order by id desc limit 3000) x),'[]'::jsonb),
  'purchases',coalesce((select jsonb_agg(jsonb_build_object(
                 'id',pu.id,'po',pu.po,'supp_id',pu.supp_id,'supp_name',pu.supp_name,'inv_no',pu.inv_no,'date',pu.date,'notes',pu.notes,
                 'amount',pu.amount,'paid',pu.paid,'incentive_used',pu.incentive_used,'status',pu.status,'ts',pu.ts,
                 'items', coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'part_id',i.part_id,'part_name',i.part_name,'qty',i.qty,'price',i.price)) from hw_purchase_items i where i.pur_id=pu.id),'[]'::jsonb)
               ) order by pu.id desc) from (select * from hw_purchases where shop_id=p_sid order by id desc limit 1500) pu),'[]'::jsonb),
  'sales',    coalesce((select jsonb_agg(jsonb_build_object(
                 'id',s.id,'inv',s.inv,'customer',s.customer,'phone',s.phone,'salesman',s.salesman,'date',s.date,
                 'subtotal',s.subtotal,'discount',s.discount,'total',s.total,'pay',s.pay,'ts',s.ts,
                 'items', coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'part_id',i.part_id,'part_name',i.part_name,'qty',i.qty,'cost',i.cost,'price',i.price)) from hw_sale_items i where i.sale_id=s.id),'[]'::jsonb)
               ) order by s.id desc) from (select * from hw_sales where shop_id=p_sid order by id desc limit 1500) s),'[]'::jsonb),
  'jobs',     coalesce((select jsonb_agg(jsonb_build_object(
                 'id',j.id,'job',j.job,'customer',j.customer,'phone',j.phone,'bike_no',j.bike_no,'bike_model',j.bike_model,'chassis',j.chassis,'engine',j.engine,
                 'mech_id',j.mech_id,'mech_name',j.mech_name,'salesman',j.salesman,'status',j.status,'parts_total',j.parts_total,'parts_cost',j.parts_cost,
                 'discount',j.discount,'labour',j.labour,'total',j.total,'pay',j.pay,'entry_ts',j.entry_ts,'exit_ts',j.exit_ts,'ts',j.ts,
                 'parts', coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'part_id',i.part_id,'part_name',i.part_name,'qty',i.qty,'cost',i.cost,'price',i.price)) from hw_job_parts i where i.job_id=j.id),'[]'::jsonb)
               ) order by j.id desc) from (select * from hw_jobs where shop_id=p_sid order by id desc limit 1500) j),'[]'::jsonb),
  'warranty', coalesce((select jsonb_agg(to_jsonb(x)-'shop_id' order by x.id desc) from (select * from hw_warranty where shop_id=p_sid order by id desc limit 2000) x),'[]'::jsonb)
);
$fn$;

-- ============================================================
-- Transaction RPCs (multi-row writes) — atomic in one call
-- ============================================================

-- ---- Parts Sale: bump inv, insert sale + items, decrement stock ----
create or replace function fn_hw_sale(p_sid bigint, p jsonb)
returns jsonb language plpgsql as $fn$
declare v_no int; v_inv text; v_id bigint; it jsonb; yr text := to_char(now(),'YYYY');
begin
  update hw_shops set inv_no = inv_no + 1 where id = p_sid returning inv_no into v_no;
  v_inv := 'INV-'||yr||'-'||v_no;
  insert into hw_sales(shop_id,inv,customer,phone,salesman,date,subtotal,discount,total,pay,ts)
    values (p_sid, v_inv, coalesce(p->>'customer',''), coalesce(p->>'phone',''), coalesce(p->>'salesman',''),
            coalesce(p->>'date',''), coalesce((p->>'subtotal')::numeric,0), coalesce((p->>'discount')::numeric,0),
            coalesce((p->>'total')::numeric,0), coalesce(p->>'pay','Cash'), coalesce((p->>'ts')::bigint,0))
    returning id into v_id;
  for it in select * from jsonb_array_elements(p->'items') loop
    insert into hw_sale_items(shop_id,sale_id,part_id,part_name,qty,cost,price)
      values (p_sid, v_id, nullif(it->>'part_id','')::bigint, coalesce(it->>'part_name',''),
              coalesce((it->>'qty')::numeric,0), coalesce((it->>'cost')::numeric,0), coalesce((it->>'price')::numeric,0));
    if (it->>'part_id') is not null and (it->>'part_id') <> '' then
      update hw_parts set stock = stock - coalesce((it->>'qty')::numeric,0)
        where id = (it->>'part_id')::bigint and shop_id = p_sid;
    end if;
  end loop;
  return jsonb_build_object('ok',true,'id',v_id,'inv',v_inv);
end $fn$;

-- ---- Purchase: bump po, insert purchase + items, increment stock, supplier bal/incentive ----
create or replace function fn_hw_purchase(p_sid bigint, p jsonb)
returns jsonb language plpgsql as $fn$
declare v_no int; v_po text; v_id bigint; it jsonb; yr text := to_char(now(),'YYYY');
        v_amount numeric := coalesce((p->>'amount')::numeric,0);
        v_paid numeric := coalesce((p->>'paid')::numeric,0);
        v_inc numeric := coalesce((p->>'incentive_used')::numeric,0);
        v_supp bigint := nullif(p->>'supp_id','')::bigint;
begin
  update hw_shops set po_no = po_no + 1 where id = p_sid returning po_no into v_no;
  v_po := 'PO-'||yr||'-'||v_no;
  insert into hw_purchases(shop_id,po,supp_id,supp_name,inv_no,date,notes,amount,paid,incentive_used,status,ts)
    values (p_sid, v_po, v_supp, coalesce(p->>'supp_name',''), coalesce(p->>'inv_no',''), coalesce(p->>'date',''),
            coalesce(p->>'notes',''), v_amount, v_paid, v_inc, coalesce(p->>'status','received'), coalesce((p->>'ts')::bigint,0))
    returning id into v_id;
  for it in select * from jsonb_array_elements(p->'items') loop
    insert into hw_purchase_items(shop_id,pur_id,part_id,part_name,qty,price)
      values (p_sid, v_id, nullif(it->>'part_id','')::bigint, coalesce(it->>'part_name',''),
              coalesce((it->>'qty')::numeric,0), coalesce((it->>'price')::numeric,0));
    if (it->>'part_id') is not null and (it->>'part_id') <> '' then
      update hw_parts set stock = stock + coalesce((it->>'qty')::numeric,0),
                          cost  = case when coalesce((it->>'price')::numeric,0) > 0 then (it->>'price')::numeric else cost end
        where id = (it->>'part_id')::bigint and shop_id = p_sid;
    end if;
  end loop;
  if v_supp is not null then
    update hw_suppliers set bal = bal + (v_amount - v_paid - v_inc), incentive = incentive - v_inc
      where id = v_supp and shop_id = p_sid;
  end if;
  return jsonb_build_object('ok',true,'id',v_id,'po',v_po);
end $fn$;

-- ---- Service Job: create with parts (deduct stock) ----
create or replace function fn_hw_job_create(p_sid bigint, p jsonb)
returns jsonb language plpgsql as $fn$
declare v_no int; v_job text; v_id bigint; it jsonb;
begin
  update hw_shops set srv_no = srv_no + 1 where id = p_sid returning srv_no into v_no;
  v_job := 'SRV-'||v_no;
  insert into hw_jobs(shop_id,job,customer,phone,bike_no,bike_model,chassis,engine,mech_id,mech_name,salesman,status,
                      parts_total,parts_cost,discount,labour,total,pay,entry_ts,ts)
    values (p_sid, v_job, coalesce(p->>'customer',''), coalesce(p->>'phone',''), coalesce(p->>'bike_no',''),
            coalesce(p->>'bike_model',''), coalesce(p->>'chassis',''), coalesce(p->>'engine',''),
            nullif(p->>'mech_id','')::bigint, coalesce(p->>'mech_name',''), coalesce(p->>'salesman',''), 'open',
            coalesce((p->>'parts_total')::numeric,0), coalesce((p->>'parts_cost')::numeric,0),
            coalesce((p->>'discount')::numeric,0), coalesce((p->>'labour')::numeric,0),
            coalesce((p->>'total')::numeric,0), coalesce(p->>'pay',''), coalesce((p->>'entry_ts')::bigint,0), coalesce((p->>'ts')::bigint,0))
    returning id into v_id;
  for it in select * from jsonb_array_elements(coalesce(p->'parts','[]'::jsonb)) loop
    insert into hw_job_parts(shop_id,job_id,part_id,part_name,qty,cost,price)
      values (p_sid, v_id, nullif(it->>'part_id','')::bigint, coalesce(it->>'part_name',''),
              coalesce((it->>'qty')::numeric,0), coalesce((it->>'cost')::numeric,0), coalesce((it->>'price')::numeric,0));
    if (it->>'part_id') is not null and (it->>'part_id') <> '' then
      update hw_parts set stock = stock - coalesce((it->>'qty')::numeric,0) where id=(it->>'part_id')::bigint and shop_id=p_sid;
    end if;
  end loop;
  return jsonb_build_object('ok',true,'id',v_id,'job',v_job);
end $fn$;

-- ---- Service Job: replace parts list (restore old stock, deduct new) + update header ----
create or replace function fn_hw_job_update(p_sid bigint, p jsonb)
returns jsonb language plpgsql as $fn$
declare v_id bigint := (p->>'id')::bigint; it jsonb; old record;
begin
  -- restore stock from existing parts
  for old in select part_id, qty from hw_job_parts where job_id=v_id and shop_id=p_sid loop
    if old.part_id is not null then
      update hw_parts set stock = stock + old.qty where id=old.part_id and shop_id=p_sid;
    end if;
  end loop;
  delete from hw_job_parts where job_id=v_id and shop_id=p_sid;
  -- insert new parts + deduct
  for it in select * from jsonb_array_elements(coalesce(p->'parts','[]'::jsonb)) loop
    insert into hw_job_parts(shop_id,job_id,part_id,part_name,qty,cost,price)
      values (p_sid, v_id, nullif(it->>'part_id','')::bigint, coalesce(it->>'part_name',''),
              coalesce((it->>'qty')::numeric,0), coalesce((it->>'cost')::numeric,0), coalesce((it->>'price')::numeric,0));
    if (it->>'part_id') is not null and (it->>'part_id') <> '' then
      update hw_parts set stock = stock - coalesce((it->>'qty')::numeric,0) where id=(it->>'part_id')::bigint and shop_id=p_sid;
    end if;
  end loop;
  update hw_jobs set
    customer=coalesce(p->>'customer',customer), phone=coalesce(p->>'phone',phone),
    bike_no=coalesce(p->>'bike_no',bike_no), bike_model=coalesce(p->>'bike_model',bike_model),
    chassis=coalesce(p->>'chassis',chassis), engine=coalesce(p->>'engine',engine),
    mech_id=nullif(p->>'mech_id','')::bigint, mech_name=coalesce(p->>'mech_name',mech_name),
    salesman=coalesce(p->>'salesman',salesman), status=coalesce(p->>'status',status),
    parts_total=coalesce((p->>'parts_total')::numeric,parts_total), parts_cost=coalesce((p->>'parts_cost')::numeric,parts_cost),
    discount=coalesce((p->>'discount')::numeric,discount), labour=coalesce((p->>'labour')::numeric,labour),
    total=coalesce((p->>'total')::numeric,total), pay=coalesce(p->>'pay',pay),
    exit_ts=coalesce((p->>'exit_ts')::bigint,exit_ts)
    where id=v_id and shop_id=p_sid;
  return jsonb_build_object('ok',true,'id',v_id);
end $fn$;

-- ---- Service Job: delete (restore stock) ----
create or replace function fn_hw_job_delete(p_sid bigint, p jsonb)
returns jsonb language plpgsql as $fn$
declare v_id bigint := (p->>'id')::bigint; old record;
begin
  for old in select part_id, qty from hw_job_parts where job_id=v_id and shop_id=p_sid loop
    if old.part_id is not null then
      update hw_parts set stock = stock + old.qty where id=old.part_id and shop_id=p_sid;
    end if;
  end loop;
  delete from hw_jobs where id=v_id and shop_id=p_sid;   -- job_parts cascade
  return jsonb_build_object('ok',true);
end $fn$;

-- ---- Parts Sale: delete/void (restore stock) ----
create or replace function fn_hw_sale_delete(p_sid bigint, p jsonb)
returns jsonb language plpgsql as $fn$
declare v_id bigint := (p->>'id')::bigint; old record;
begin
  for old in select part_id, qty from hw_sale_items where sale_id=v_id and shop_id=p_sid loop
    if old.part_id is not null then
      update hw_parts set stock = stock + old.qty where id=old.part_id and shop_id=p_sid;
    end if;
  end loop;
  delete from hw_sales where id=v_id and shop_id=p_sid;
  return jsonb_build_object('ok',true);
end $fn$;

-- ---- Purchase: delete (reverse stock + supplier bal) ----
create or replace function fn_hw_purchase_delete(p_sid bigint, p jsonb)
returns jsonb language plpgsql as $fn$
declare v_id bigint := (p->>'id')::bigint; old record; h record;
begin
  select * into h from hw_purchases where id=v_id and shop_id=p_sid;
  if not found then return jsonb_build_object('ok',true); end if;
  for old in select part_id, qty from hw_purchase_items where pur_id=v_id and shop_id=p_sid loop
    if old.part_id is not null then
      update hw_parts set stock = greatest(0, stock - old.qty) where id=old.part_id and shop_id=p_sid;
    end if;
  end loop;
  if h.supp_id is not null then
    update hw_suppliers set bal = bal - (h.amount - h.paid - h.incentive_used), incentive = incentive + h.incentive_used
      where id=h.supp_id and shop_id=p_sid;
  end if;
  delete from hw_purchases where id=v_id and shop_id=p_sid;
  return jsonb_build_object('ok',true);
end $fn$;

-- Done. Run once in Supabase → SQL Editor.
